In [12]:
import sklearn as sk
from sklearn import datasets
# import some data
iris = datasets.load_iris()
#retrieve the data
X = iris.data
y = iris.target

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(y_test.shape)
print(X_train.shape)

(45,)
(105, 4)


In [60]:
#DecisionTree
irisFeatures = iris.feature_names #Our Labels
print(irisFeatures)

import pandas as pd
from collections import Counter
import math

def calculate_entropy(y):
    """Calculates the entropy of a target variable."""
    hist = Counter(y)
    probs = [count / len(y) for count in hist.values()]
    return -sum(p * math.log2(p) for p in probs if p > 0)

def split_data(df, attribute):
    """Splits the dataset based on the values of a given attribute."""
    splits = {}
    for value in df[attribute].unique():
        splits[value] = df[df[attribute] == value]
    return splits

def select_best_attribute(df, target_attribute, attributes):
    """Selects the attribute that gives the maximum information gain."""
    best_gain = 0
    best_attribute = None
    entropy_parent = calculate_entropy(df[target_attribute])

    for attribute in attributes:
        gain = entropy_parent
        splits = split_data(df, attribute)
        for subset in splits.values():
            prob = len(subset) / len(df)
            gain -= prob * calculate_entropy(subset[target_attribute])

        if gain > best_gain:
            best_gain = gain
            best_attribute = attribute
    return best_attribute

class DecisionTreeClassifierSimplified:
    def __init__(self):
        self.tree = None

    def fit(self, df, target_attribute):
        self.tree = self._build_tree(df, target_attribute, df.columns.drop(target_attribute).tolist())

    def _build_tree(self, df, target_attribute, attributes):
        # Base cases:
        if len(df[target_attribute].unique()) == 1:
            return df[target_attribute].iloc[0]  # Return the single class

        if not attributes:
            return Counter(df[target_attribute]).most_common(1)[0][0] # Return majority class

        # Recursive step:
        best_attribute = select_best_attribute(df, target_attribute, attributes)

        if best_attribute is None: # No information gain
            return Counter(df[target_attribute]).most_common(1)[0][0]

        tree = {best_attribute: {}}
        remaining_attributes = [attr for attr in attributes if attr != best_attribute]
        splits = split_data(df, best_attribute)

        for value, subset in splits.items():
            tree[best_attribute][value] = self._build_tree(subset.copy(), target_attribute, remaining_attributes)

        return tree

    def predict(self, instance):
        def _traverse_tree(tree, instance):
            if not isinstance(tree, dict):
                return tree  # Leaf node

            attribute = list(tree.keys())[0]
            value = instance.get(attribute)
            if value in tree[attribute]:
                return _traverse_tree(tree[attribute][value], instance)
            else:
                # Handle unseen values (simplified: return majority of training target)
                # A more robust approach would involve handling missing branches
                return Counter(self._get_all_targets(self.tree)).most_common(1)[0][0]

        return _traverse_tree(self.tree, instance)

    def _get_all_targets(self, tree):
        """Helper function to extract all target values from the tree (for unseen values)."""
        targets = []
        if not isinstance(tree, dict):
            return [tree]
        for subtree in tree.values():
            if isinstance(subtree, dict):
                for inner_subtree in subtree.values():
                    targets.extend(self._get_all_targets(inner_subtree))
            else:
                targets.append(subtree)
        return targets

# Example Usage:
data =  X

irisdf = pd.DataFrame(data)
target_attribute = 'sepal length'

# Train the simplified decision tree
simplified_tree = DecisionTreeClassifierSimplified()
simplified_tree.fit(irisdf, target_attribute)

print("Trained Decision Tree (Simplified):")
import json
print(json.dumps(simplified_tree.tree, indent=2))

# Make a prediction
new_instance = {'sepal_length': '6', 'Temperature': 'Mild', 'Humidity': 'High', 'Windy': 'False'}
prediction = simplified_tree.predict(new_instance)
print(f"\nPrediction for {new_instance}: {prediction}")

new_instance_unseen = {'Outlook': 'Unknown', 'Temperature': 'Cool', 'Humidity': 'Normal', 'Windy': 'True'}
prediction_unseen = simplified_tree.predict(new_instance_unseen)
print(f"Prediction for unseen value {new_instance_unseen}: {prediction_unseen}")

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [39]:
#DecisionTree
irisFeatures = iris.feature_names #Our Labels
print(irisFeatures)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [15]:
def class_counts(rows):
    #Counts the number of each type of example in a dataset"
    counts = {}
    for row in rows:
        label = row[-1]
        if label not in counts:
            counts[label] = 0
        counts[label] += 1
    return counts

In [16]:
class_counts(iris)

{'a': 1, 't': 1, 'e': 3, 's': 2, 'R': 1}

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
unique_vals()

In [ ]:
import pandas as pd
from collections import Counter
import math

def calculate_entropy(y):
    """Calculates the entropy of a target variable."""
    hist = Counter(y)
    probs = [count / len(y) for count in hist.values()]
    return -sum(p * math.log2(p) for p in probs if p > 0)

def split_data(df, attribute):
    """Splits the dataset based on the values of a given attribute."""
    splits = {}
    for value in df[attribute].unique():
        splits[value] = df[df[attribute] == value]
    return splits

def select_best_attribute(df, target_attribute, attributes):
    """Selects the attribute that gives the maximum information gain."""
    best_gain = 0
    best_attribute = None
    entropy_parent = calculate_entropy(df[target_attribute])

    for attribute in attributes:
        gain = entropy_parent
        splits = split_data(df, attribute)
        for subset in splits.values():
            prob = len(subset) / len(df)
            gain -= prob * calculate_entropy(subset[target_attribute])

        if gain > best_gain:
            best_gain = gain
            best_attribute = attribute
    return best_attribute

class DecisionTreeClassifierSimplified:
    def __init__(self):
        self.tree = None

    def fit(self, df, target_attribute):
        self.tree = self._build_tree(df, target_attribute, df.columns.drop(target_attribute).tolist())

    def _build_tree(self, df, target_attribute, attributes):
        # Base cases:
        if len(df[target_attribute].unique()) == 1:
            return df[target_attribute].iloc[0]  # Return the single class

        if not attributes:
            return Counter(df[target_attribute]).most_common(1)[0][0] # Return majority class

        # Recursive step:
        best_attribute = select_best_attribute(df, target_attribute, attributes)

        if best_attribute is None: # No information gain
            return Counter(df[target_attribute]).most_common(1)[0][0]

        tree = {best_attribute: {}}
        remaining_attributes = [attr for attr in attributes if attr != best_attribute]
        splits = split_data(df, best_attribute)

        for value, subset in splits.items():
            tree[best_attribute][value] = self._build_tree(subset.copy(), target_attribute, remaining_attributes)

        return tree

    def predict(self, instance):
        def _traverse_tree(tree, instance):
            if not isinstance(tree, dict):
                return tree  # Leaf node

            attribute = list(tree.keys())[0]
            value = instance.get(attribute)
            if value in tree[attribute]:
                return _traverse_tree(tree[attribute][value], instance)
            else:
                # Handle unseen values (simplified: return majority of training target)
                # A more robust approach would involve handling missing branches
                return Counter(self._get_all_targets(self.tree)).most_common(1)[0][0]

        return _traverse_tree(self.tree, instance)

    def _get_all_targets(self, tree):
        
        targets = []
        if not isinstance(tree, dict):
            return [tree]
        for subtree in tree.values():
            if isinstance(subtree, dict):
                for inner_subtree in subtree.values():
                    targets.extend(self._get_all_targets(inner_subtree))
            else:
                targets.append(subtree)
        return targets


data = iris
irisdf = pd.DataFrame(X)
target_attribute = 'sepal length'

# Train the simplified decision tree
simplified_tree = DecisionTreeClassifierSimplified()
simplified_tree.fit(irisdf, target_attribute)

print("Trained Decision Tree:")
import json
print(json.dumps(simplified_tree.tree, indent=2))

# Make a prediction
new_instance = {'sepal length': '6', 'sepal width': '5', 'pedal length': '6', 'pedal width': '5'}
prediction = simplified_tree.predict(new_instance)
print(f"\nPrediction for {new_instance}: {prediction}")

new_instance_unseen = {'sepal length': '5', 'sepal width': '4', 'pedal length': '5', 'pedal width': '3'}
prediction_unseen = simplified_tree.predict(new_instance_unseen)
print(f"Prediction for unseen value {new_instance_unseen}: {prediction_unseen}")

KeyError: "['sepal length'] not found in axis"

In [ ]:
#Ensemble Model

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
list(data.target_names)
['malignant', 'benign']

In [22]:
#LSTM for Time Series Forcaseting

import os
import torch
import torchvision
from torch import nn, optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

Gasdf = pd.read_csv("40-Day_Gas_Price_Dataset.csv")
print(Gasdf.head())


         Date     Price
0  2024-01-01  3.014901
1  2024-01-02  3.005852
2  2024-01-03  3.039431
3  2024-01-04  3.075691
4  2024-01-05  3.032975


In [66]:
GasArray = np.asarray(Gasdf)
CompatibleGasArray = GasArray.astype(float32)
print(GasArray.dtype)
#training_data = torch.Tensor(GasArray)

NameError: name 'float32' is not defined

In [ ]:
batchsize=100
#Transform the dataframe to a tensor for training. Split the ata first

GasArray = Gasdf.values
GasArray2 = np.array(Gasdf)
GasArrayFloat = GasArray2.astype(np.float32)
#GasTensor = torch.tensor(GasArray, dtype=torch.float32)
'''GasArray = np.asarray(Gasdf)
training_data = torch.Tensor(GasArray)'''
#datasets.FashionMNIST(root="40-Day_Gas_Price_Dataset.csv", train=True, transform=transforms.ToTensor())


train_dataloader = DataLoader(training_data, batch_size=batchsize)
test_dataloader = DataLoader(test_data, batch_size=batchsize)


ValueError: could not convert string to float: '2024-01-01'

In [40]:
sequence_len = 28
input_len = 28
hidden_size = 128
num_layers = 2
num_classes = 10
num_epochs = 5
learning_rate = 0.01

In [41]:
class LSTM(nn.Module):
    def __init__(self, input_len, hidden_size, num_class, num_layers):
        super(LSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_len, hidden_size, num_layers, batch_first=True)
        self.output_layer = nn.Linear(hidden_size, num_classes)
    
    def forward(self, X):
        hidden_states = torch.zeros(self.num_layers, X.size(0), self.hidden_size)
        cell_states = torch.zeros(self.num_layers, X.size(0), self.hidden_size)
        out, _ = self.lstm(X, (hidden_states, cell_states))
        out = self.output_layer(out[:, -1, :])
        return out

In [42]:
model = LSTM(input_len, hidden_size, num_classes, num_layers)
print(model)


LSTM(
  (lstm): LSTM(28, 128, num_layers=2, batch_first=True)
  (output_layer): Linear(in_features=128, out_features=10, bias=True)
)


In [43]:
loss_func = nn.CrossEntropyLoss()
sgd = optim.SGD(model.parameters(), lr=learning_rate)
adam = optim.Adam(model.parameters(), lr=learning_rate)


In [44]:
def train(num_epochs, model, train_dataloader, loss_func, optimizer):
    total_steps = len(train_dataloader)

    for epoch in range(num_epochs):
        for batch, (images, labels) in enumerate(train_dataloader):
            images = images.reshape(-1, sequence_len, input_len)
            
            output = model(images)
            loss = loss_func(output, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if (batch+1)%100 == 0:
                print(f"Epoch: {epoch+1}; Batch {batch+1} / {total_steps}; Loss: {loss.item():>4f}")

In [45]:
train(num_epochs, model, train_dataloader, loss_func, adam)


NameError: name 'train_dataloader' is not defined

In [67]:
test_predictions, test_labels = next(iter(test_dataloader))
test_labels



NameError: name 'test_dataloader' is not defined

In [ ]:
correct = [1 for i in range(100) if predicted[i] == test_labels[i]]



In [ ]:
#Ensemble Model

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
list(data.target_names)
['malignant', 'benign']

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Add bias term to X_train and X_test
X_train_b = np.c_[np.ones((X_train.shape[0], 1)), X_train]
X_test_b = np.c_[np.ones((X_test.shape[0], 1)), X_test]

print(f"Train shape: {X_train_b.shape}, Test shape: {X_test_b.shape}")

In [46]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [48]:
def gradient_descent(X, y, learning_rate=0.01, epochs=1000):
    m, n = X.shape
    theta = np.zeros(n)
    loss_history = []
    predictionVector = np.array

    for epoch in range(epochs):
        predictions = sigmoid(X @ theta)  # Compute predictions
        gradients = (1/m) * X.T @ (predictions - y)  # Compute gradients
        theta -= learning_rate * gradients  # Update parameters


        loss = -np.mean(y * np.log(predictions + 1e-8) + (1 - y) * np.log(1 - predictions + 1e-8))
        loss_history.append(loss)

        if epoch % 100 == 0:

            print(f"Epoch {epoch}: Loss = {loss:.4f}")

    return theta, loss_history

In [49]:
theta_gd, loss_history = gradient_descent(X_train_b, y_train, learning_rate=0.1, epochs=1000)

print("\nEstimated Coefficients:", theta_gd)

NameError: name 'X_train_b' is not defined

In [ ]:
plt.plot(loss_history)
plt.xlabel("Epochs")
plt.ylabel("Binary Cross-Entropy Loss")
plt.title("Loss Curve for Logistic Regression")
plt.show()

In [51]:
def normalize(df):
    return (df - df.min()) / (df.max() - df.min())

    normdf = min_max_normalize(df)
    normdf.to_csv('normalized_data.csv', index=False)

normdf = normalize(data)
print(normdf)
     

[[0.64102564 0.43589744 0.16666667 0.01282051]
 [0.61538462 0.37179487 0.16666667 0.01282051]
 [0.58974359 0.3974359  0.15384615 0.01282051]
 [0.57692308 0.38461538 0.17948718 0.01282051]
 [0.62820513 0.44871795 0.16666667 0.01282051]
 [0.67948718 0.48717949 0.20512821 0.03846154]
 [0.57692308 0.42307692 0.16666667 0.02564103]
 [0.62820513 0.42307692 0.17948718 0.01282051]
 [0.55128205 0.35897436 0.16666667 0.01282051]
 [0.61538462 0.38461538 0.17948718 0.        ]
 [0.67948718 0.46153846 0.17948718 0.01282051]
 [0.6025641  0.42307692 0.19230769 0.01282051]
 [0.6025641  0.37179487 0.16666667 0.        ]
 [0.53846154 0.37179487 0.12820513 0.        ]
 [0.73076923 0.5        0.14102564 0.01282051]
 [0.71794872 0.55128205 0.17948718 0.03846154]
 [0.67948718 0.48717949 0.15384615 0.03846154]
 [0.64102564 0.43589744 0.16666667 0.02564103]
 [0.71794872 0.47435897 0.20512821 0.02564103]
 [0.64102564 0.47435897 0.17948718 0.02564103]
 [0.67948718 0.42307692 0.20512821 0.01282051]
 [0.64102564 

In [ ]:
trainSet = normdf[0:134]
print(trainSet)
trainArray = trainSet.to_numpy()

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(y_test.shape)
     

(45,)


In [57]:
from collections import Counter
#KNN function

class KNN:
  def __init__(self,k):
    self.k = k
    self.trainingData = None;
    self.trainingLabels = None;

  def fit(self, X, y):
    self.training_data = X
    self.training_labels = y

  def euclidean_distance(p, q):
    return np.sqrt(np.sum((np.array(p) - np.array(q)) ** 2))


  def predict(self, X_test):
    predictions = []
    for test_point in X_test:
      distances = []

      for i, training_point in enumerate(self.training_data):
        #iterates through the test sets and calculates the euclidean distance between the 2 points
        distance = euclidean_distance(test_point, training_point)
        distances.append((distance, i))
        #storing distances as a tuple
        #i is each pair of points. ex: point 0 is (training[0], test[0], and point 2 and point 3 and so on)
        #using the lambda funtion to sort the list by the first element of each point which is the distance(distance, i)
        distances.sort(key=lambda x: x[0])

        k_nearest_indices = [index for (_, index) in distances[:self.k]]
        k_nearest = distances[:self.k]
        #neighbor_labels = [self.training_labels[i] for i in k_nearest]
        neighbor_labels = self.training_labels[k_nearest_indices]
        '''prediction = max(set(neighbor_labels), key=neighbor_labels.count)
        predictions.append(prediction)'''

        most_common_label = Counter(neighbor_labels).most_common(1)[0][0]
        predictions.append(most_common_label)

    return predictions

In [58]:
X, y = load_breast_cancer().data, load_breast_cancer().target
knn = KNN(k=1)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)


#this line of code is giving errors and I have no idea why.
accuracy = accuracy_score(y_test, predictions)
print(f"\nAccuracy: {accuracy:.4f}")

class_names = columnNames
titles_options = [
    ("Confusion matrix, without normalization", None),
    ("Normalized confusion matrix", "true"),
]


for titles, normalize in titles_options:
    display = ConfusionMatrixDisplay.from_predictions(
        y_test, predictions,  # Pass true labels (y_test) and predictions
        display_labels=class_names,
        cmap=plt.cm.inferno,
        normalize=normalize,
    )
    display.ax_.set_title(titles)
    print(titles)
    print(display.confusion_matrix)

plt.show()

NameError: name 'euclidean_distance' is not defined